[package]
name = "linkgen"
version = "0.1.0"
authors = ["John J. Camp <jjcamp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "^1.8"
